### ISSUE TITLE
error

### ISSUE THREAD

**Issue by TtlyLynzie** [kelciour/deepl-translator#6]
Debug info:
Anki 2.1.50 (26d40c3a) Python 3.9.7 Qt 6.2.3 PyQt 6.2.3
Platform: Mac 12.3.1
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2022-04-18 20:09:48

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "json", line 231, in dumps
  File "json.encoder", line 199, in encode
  File "json.encoder", line 257, in iterencode
  File "json.encoder", line 179, in default
TypeError: Object of type DeepLTranslator is not JSON serializable

**Comment by cleinias** [comment]
Confirmed, I got exactly the same error: 

Debug info:
Anki 2.1.51 (cf78a555) Python 3.10.4 Qt 6.3.0 PyQt 6.3.0
Platform: Linux
Flags: frz=False ao=True sv=2
Add-ons, last update check: 2022-05-02 11:53:31

Caught exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/aqt/webview.py", line 42, in cmd
    return json.dumps(self.onCmd(str))
  File "/usr/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DeepLTranslator is not JSON serializable

**Comment by srepn** [comment]
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-14 04:21:35

Caught exception:
Traceback (most recent call last):
  File "aqt.webview", line 42, in cmd
  File "json", line 231, in dumps
  File "json.encoder", line 199, in encode
  File "json.encoder", line 257, in iterencode
  File "json.encoder", line 179, in default
TypeError: Object of type DeepLTranslator is not JSON serializable

**Comment by srepn** [comment]
Qt5 version have the same error as well.
