### ISSUE TITLE
Error message when opening translation UI

### ISSUE THREAD

**Issue by amperag** [kelciour/deepl-translator#7]
When opening up the translation UI the following error message appears. Translation can be done nonetheless.

```
Fehler
Es ist ein Fehler aufgetreten. Bitte starten Sie Anki neu und halten Sie während des Startvorgangs die Umschalttaste gedrückt, damit Anki die installierten Erweiterungen temporär deaktiviert.
Wenn das Problem nur auftritt, wenn die Erweiterungen aktiviert sind, dann benutzen Sie bitte den Menueintrag Extras > Erweiterungen um die problembehaftete Erweiterung durch selektives Deaktivieren herauszufinden.
Wenn Sie die entsprechende Erweiterung herausgefunden haben, dann bitten wir, dass Sie sich mit einem entsprechenden Problembericht an die Support-Seite für Erweiterungen wenden, damit der Fehler behoben werden kann.
Debuginformationen:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-07-25 06:03:26

Caught exception:
Traceback (most recent call last):
File "aqt.webview", line 42, in cmd
File "json", line 231, in dumps
File "json.encoder", line 199, in encode
File "json.encoder", line 257, in iterencode
File "json.encoder", line 179, in default
TypeError: Object of type DeepLTranslator is not JSON serializable
```

**Comment by amperag** [comment]
Thank you @kelciour for fixing this!
